### ISSUE TITLE
URB_CONTROL in

### ISSUE THREAD

**Issue by elegos** [google/gousb#31]
Hello!

I'm trying to reverse-engineer a windows-only USB data transfer protocol of one of my devices.

I see a bunch of URB_CONTROL requests / replies on endpoint 0x00 (OUT) and 0x80 (IN). I'm confused though on how I can select the endpoint 0x80 with `func (d *Device) Control(rType, request uint8, val, idx uint16, data []byte) (int, error)`.

May you please help me sorting this out?

Thanks :)

EDIT: the default interface has 1 alternative configuration with 2 endpoints available: `0x00(1,OUT)` and `0x81(1,IN)`

**Comment by zagrodzki** [comment]
You're not expected to select and endpoint, just use the correct request type. Even better still, look at section 9.4 of the USB 2.0 spec ("Standard Device Requests"), it lists a set of common requests with their meaning. It's very likely most of these requests are related to things like e.g. selecting a configuration or selecting an alternate setting of an interface - in which case you should use the designated gousb functions (e.g. Device.Config or Config.Interface) rather than hand-crafting the control requests.

Background:
Whether the endpoint value will be IN (0x80) or OUT (0x00) depends on the type of the control request (i.e. rType) - bit 7 of rType indicates a write (0, OUT) or read (1, IN), see section 9.3 USB 2.0 spec.

Both endpoint values 0x80 and 0x00 refer to endpoint number 0, bit 7 only indicates the direction of communication, not the endpoint number as such, see 5.5.2 of the spec.
